'use client';

import { useEffect, useState } from 'react';
import { Bot, Loader2, Play, RefreshCw, ShieldAlert, Clock } from 'lucide-react';
import { SectionTitle, PortalCard, Badge } from '@/components/ui/portal-card';
import { formatRelativeTime } from '@/lib/utils';

type Agent = { name: string; description: string };
type Status = {
  enabled: boolean;
  agents: Agent[];
  last_run: string | null;
  summary: Record<string, unknown> | null;
  rules_updated_at: string | null;
};

type Threat = {
  id: string;
  title: string;
  description: string;
  type: string;
  severity: string;
  agent: string | null;
  autoGenerated?: boolean;
  publishedAt: string;
};

const severityTone = (s: string): 'danger' | 'warning' | 'info' => {
  if (s === 'CRITICAL' || s === 'HIGH') return 'danger';
  if (s === 'MEDIUM') return 'warning';
  return 'info';
};

export default function ThreatHunterPage() {
  const [status, setStatus] = useState<Status | null>(null);
  const [threats, setThreats] = useState<Threat[]>([]);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [runMsg, setRunMsg] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const [sRes, tRes] = await Promise.all([
        fetch('/api/proxy/agents/status', { cache: 'no-store' }),
        fetch('/api/threats', { cache: 'no-store' }),
      ]);
      const sJson = await sRes.json();
      const tJson = await tRes.json();
      if (!sRes.ok || !sJson.success) throw new Error(sJson.error || 'Failed to load agent status');
      setStatus(sJson.data as Status);
      const all = (tJson.data as Threat[]) || [];
      setThreats(all.filter((t) => t.autoGenerated));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  }

  async function runAgents() {
    setRunning(true);
    setRunMsg(null);
    setError(null);
    try {
      const res = await fetch('/api/proxy/agents/run', { method: 'POST' });
      const json = await res.json();
      if (!res.ok || !json.success) throw new Error(json.error || 'Run failed');
      setRunMsg(JSON.stringify(json.data || {}));
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Run failed');
    } finally {
      setRunning(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <SectionTitle
          title="AI Threat-Hunter"
          subtitle="Autonomous agents that scan registries and networks for impersonation, then auto-publish threats and notify regulators"
        />
        <button
          onClick={runAgents}
          disabled={running}
          className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-gradient-to-br from-primary-600 to-accent-600 px-5 text-sm font-medium text-white disabled:opacity-50"
        >
          {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
          {running ? 'Hunting...' : 'Run Hunt Now'}
        </button>
      </div>

      {error && <p className="text-sm text-red-600">{error}</p>}
      {runMsg && (
        <p className="rounded-xl border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">
          Hunt complete: {runMsg}
        </p>
      )}

      {loading && !status ? (
        <div className="flex h-40 items-center justify-center text-muted-foreground">
          <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Loading agents...
        </div>
      ) : (
        status && (
          <PortalCard>
            <div className="mb-3 flex flex-wrap items-center gap-3 text-sm">
              <Badge tone={status.enabled ? 'success' : 'neutral'}>
                {status.enabled ? 'Auto-run enabled' : 'Manual only'}
              </Badge>
              {status.last_run && (
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <Clock className="h-4 w-4" /> Last run {formatRelativeTime(status.last_run)}
                </span>
              )}
              {status.rules_updated_at && (
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <ShieldAlert className="h-4 w-4" /> Rules updated {formatRelativeTime(status.rules_updated_at)}
                </span>
              )}
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {status.agents.map((a) => (
                <div key={a.name} className="flex items-start gap-3 rounded-xl border border-border p-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary">
                    <Bot className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="text-sm font-semibold">{a.name}</div>
                    <div className="text-xs text-muted-foreground">{a.description}</div>
                  </div>
                </div>
              ))}
            </div>
          </PortalCard>
        )
      )}

      <div className="flex items-center justify-between">
        <h2 className="font-semibold">Auto-generated threats</h2>
        <button
          onClick={load}
          className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-input px-3 text-sm text-muted-foreground hover:text-foreground"
        >
          <RefreshCw className="h-4 w-4" /> Refresh
        </button>
      </div>

      {threats.length === 0 ? (
        <PortalCard className="text-sm text-muted-foreground">
          No auto-generated threats yet. Run a hunt to see the agents discover impersonating domains.
        </PortalCard>
      ) : (
        <div className="space-y-3">
          {threats.map((t) => (
            <PortalCard key={t.id}>
              <div className="mb-1 flex flex-wrap items-center gap-2">
                <h3 className="text-base font-semibold">{t.title}</h3>
                <Badge tone={severityTone(t.severity)}>{t.severity}</Badge>
                <Badge tone="neutral">{t.type}</Badge>
                {t.agent && <Badge tone="info">{t.agent}</Badge>}
              </div>
              <p className="text-sm text-muted-foreground">{t.description}</p>
            </PortalCard>
          ))}
        </div>
      )}
    </div>
  );
}