import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import type { RiskLevel, ThreatType, RegulatorAlertStatus } from '@prisma/client';

const AGENT_KEY = process.env.AGENT_INTERNAL_KEY || 'verifin-agent-internal-key';

const THREAT_TYPES: ThreatType[] = ['PHISHING', 'MALWARE', 'SCAM', 'FRAUD', 'IMPERSONATION', 'DATA_LEAK', 'OTHER'];
const SEVERITIES: RiskLevel[] = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

type Finding = {
  title?: string;
  description?: string;
  type?: string;
  severity?: string;
  indicators?: Record<string, unknown>;
  source?: string;
  sourceUrl?: string;
  confidence?: number;
  agent?: string;
  regulator?: string | null;
};

function cleanString(value: unknown, fallback: string, max = 2000): string {
  return String(value ?? fallback).trim().slice(0, max) || fallback;
}

export async function POST(request: Request) {
  try {
    const key = request.headers.get('x-agent-key');
    if (!key || key !== AGENT_KEY) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    let body: { findings?: Finding[] };
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ success: false, error: 'Invalid JSON body' }, { status: 400 });
    }

    const findings = Array.isArray(body?.findings) ? body.findings.slice(0, 100) : [];
    const created: string[] = [];
    const alertsCreated: string[] = [];
    const notified: string[] = [];
    let deduped = 0;

    for (const f of findings) {
      const title = cleanString(f.title, 'Unnamed agent finding', 200);
      const source = cleanString(f.source, 'agent', 100);

      const existing = await prisma.threatFeed.findFirst({
        where: { source, title },
        orderBy: { publishedAt: 'desc' },
      });
      if (existing) {
        deduped += 1;
        continue;
      }

      const severity: RiskLevel = SEVERITIES.includes(f.severity as RiskLevel)
        ? (f.severity as RiskLevel)
        : 'MEDIUM';
      const type: ThreatType = THREAT_TYPES.includes(f.type as ThreatType)
        ? (f.type as ThreatType)
        : 'OTHER';

      const threat = await prisma.threatFeed.create({
        data: {
          title,
          description: cleanString(f.description, 'Auto-generated finding from threat-hunter.'),
          type,
          severity,
          indicators: (f.indicators ?? {}) as object,
          source,
          sourceUrl: f.sourceUrl ? String(f.sourceUrl).slice(0, 500) : null,
          isActive: true,
          publishedAt: new Date(),
          agent: f.agent ? String(f.agent).slice(0, 100) : null,
          autoGenerated: true,
          confidence: typeof f.confidence === 'number' ? f.confidence : null,
        },
      });
      created.push(threat.id);

      if (f.regulator && (severity === 'HIGH' || severity === 'CRITICAL')) {
        const alert = await prisma.regulatorAlert.create({
          data: {
            threatId: threat.id,
            title: `[${type}] ${title}`,
            description: threat.description,
            regulator: cleanString(f.regulator, 'SEBI', 50),
            threatType: type,
            severity,
            agent: threat.agent,
            indicators: (f.indicators ?? null) as object | null,
            confidence: threat.confidence ?? 0,
            status: 'NEW' as RegulatorAlertStatus,
            sourceUrl: threat.sourceUrl,
          },
        });
        const notifiedAlert = await notifyRegulator(alert.id, threat.title, threat.description, severity, type, alert.regulator);
        alertsCreated.push(alert.id);
        if (notifiedAlert) notified.push(alert.id);
      }
    }

    return NextResponse.json({
      success: true,
      data: {
        created: created.length,
        deduped,
        alerts: alertsCreated.length,
        notified: notified.length,
      },
    });
  } catch (error) {
    console.error('[agents/publish]', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

async function notifyRegulator(
  alertId: string,
  title: string,
  description: string,
  severity: RiskLevel,
  type: ThreatType,
  regulator: string
): Promise<boolean> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.warn(
      `[agents/publish] regulator alert ${alertId} created for ${regulator} but NOT emailed: RESEND_API_KEY is not configured. ` +
        `Set it in apps/web/.env (and REGULATOR_EMAIL) to enable regulator notifications.`
    );
    return false;
  }
  const to = (process.env.REGULATOR_EMAIL || 'notifications@verifin.ai').trim();
  const from = process.env.EMAIL_FROM || 'VeriFin AI ThreatHunter <onboarding@resend.dev>';
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from,
        to: [to],
        subject: `[VeriFin ThreatHunter] ${severity} ${type} — ${title.slice(0, 120)}`,
        html: `
          <h2>${severity} ${type} — ${title}</h2>
          <p><strong>Regulator:</strong> ${regulator}</p>
          <p>${description.replace(/</g, '&lt;').replace(/\n/g, '<br/>')}</p>
          <p style="color:#888;font-size:12px">Auto-generated by the VeriFin AI agentic threat-hunter. Review in the admin console.</p>
        `,
      }),
    });
    if (res.ok) {
      await prisma.regulatorAlert.update({
        where: { id: alertId },
        data: { notifiedAt: new Date() },
      });
      return true;
    }
    console.error('[agents/publish] Resend error', res.status, await res.text());
    return false;
  } catch (error) {
    console.error('[agents/publish] Resend exception', error);
    return false;
  }
}