'use client';

import { Settings, ShieldAlert, Database } from 'lucide-react';
import { PortalCard, SectionTitle } from '@/components/ui/portal-card';

export default function AdminSettingsPage() {
  return (
    <div className="max-w-2xl space-y-6">
      <SectionTitle title="Settings" subtitle="System configuration" />

      <PortalCard>
        <h3 className="mb-3 flex items-center gap-2 text-base font-semibold">
          <ShieldAlert className="h-4 w-4 text-slate-700" /> Platform
        </h3>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li>• Investors can scan text, URLs, images, and audio.</li>
          <li>• Institutions publish signed, QR-verifiable notices.</li>
          <li>• Admins manage the threat feed and flagged content.</li>
        </ul>
      </PortalCard>

      <PortalCard>
        <h3 className="mb-3 flex items-center gap-2 text-base font-semibold">
          <Database className="h-4 w-4 text-slate-700" /> Data sources
        </h3>
        <p className="text-sm text-muted-foreground">
          Detection results are persisted to the platform database. PDF reports are generated by the
          backend ML service.
        </p>
      </PortalCard>

      <PortalCard>
        <h3 className="mb-3 flex items-center gap-2 text-base font-semibold">
          <Settings className="h-4 w-4 text-slate-700" /> Advanced
        </h3>
        <p className="text-sm text-muted-foreground">
          Role escalation is performed from the Users page. Key rotation for institutions is handled
          per-institution.
        </p>
      </PortalCard>
    </div>
  );
}
